/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_ejercicio9;

import javax.swing.JOptionPane;
import jdk.nashorn.internal.scripts.JO;

/**
 *
 * @author GABRIEL
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMontoI = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtMontoF = new javax.swing.JTextField();
        cmdBorrar = new javax.swing.JButton();
        cmdCalcular1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtCosto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("ALQUILER - TARJETAS PARA LLAMADAS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 18, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel2.setText("Digite el monto inicial:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        txtMontoI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMontoIKeyTyped(evt);
            }
        });
        jPanel1.add(txtMontoI, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 180, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel3.setText("Digite el monto final:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        txtMontoF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMontoFKeyTyped(evt);
            }
        });
        jPanel1.add(txtMontoF, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 180, 30));

        cmdBorrar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmdBorrar.setText("Borrar");
        cmdBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBorrarActionPerformed(evt);
            }
        });
        jPanel1.add(cmdBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 80, 30));

        cmdCalcular1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmdCalcular1.setText("Calcular");
        cmdCalcular1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCalcular1ActionPerformed(evt);
            }
        });
        jPanel1.add(cmdCalcular1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 80, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel4.setText("Costo de la llamada:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 245, -1, -1));

        txtCosto.setEditable(false);
        jPanel1.add(txtCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 240, 180, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBorrarActionPerformed
        // TODO add your handling code here:
        txtMontoI.setText("");
        txtMontoF.setText("");
        txtCosto.setText("");
        txtMontoI.requestFocusInWindow();
    }//GEN-LAST:event_cmdBorrarActionPerformed

    private void cmdCalcular1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCalcular1ActionPerformed
        // TODO add your handling code here:
        if (txtMontoI.getText().isEmpty() &&txtMontoF.getText().isEmpty() ) {
            JOptionPane.showMessageDialog(this, "Campos vacíos. Por favor llénelos", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtMontoI.requestFocusInWindow();
        }
        else if (txtMontoI.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite el monto inicial", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtMontoI.requestFocusInWindow();
        }
        else if (txtMontoF.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite el monto final", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtMontoF.requestFocusInWindow();
        }
        else if (txtMontoI.getText().equals(".")) {
            JOptionPane.showMessageDialog(this, "No puede operar puntos", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtMontoI.setText("");
            txtMontoI.requestFocusInWindow();
        }
        else if (txtMontoF.getText().equals(".")) {
            JOptionPane.showMessageDialog(this, "No puede operar puntos", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtMontoF.setText("");
            txtMontoF.requestFocusInWindow();
        }
        else if (txtMontoI.getText().equals(".") && txtMontoF.getText().equals(".")) {
            JOptionPane.showMessageDialog(this, "No puede operar puntos", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtMontoI.setText("");
            txtMontoF.setText("");
            txtMontoI.requestFocusInWindow();
        }
        else {
            double mI, mF, mC, costoLlamada;
            mI = Double.parseDouble(txtMontoI.getText());
            mF = Double.parseDouble(txtMontoF.getText());
            mC = mI - mF;
            costoLlamada = (mC * 0.20) + mC;
            txtCosto.setText(""+costoLlamada);
        }
    }//GEN-LAST:event_cmdCalcular1ActionPerformed

    private void txtMontoIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMontoIKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar(); 
        if(!Character.isDigit(c) && c != '.') { 
              getToolkit().beep(); 
              evt.consume(); 
        }
        if (c == '.' && txtMontoI.getText().contains(".")) {
            evt.consume(); 
        }
    }//GEN-LAST:event_txtMontoIKeyTyped

    private void txtMontoFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMontoFKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) && c!='.') {
            getToolkit().beep();
            evt.consume();
        }
        if (c == '.' && txtMontoF.getText().contains(".")) {
            evt.consume();
        }
    }//GEN-LAST:event_txtMontoFKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdBorrar;
    private javax.swing.JButton cmdCalcular1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCosto;
    private javax.swing.JTextField txtMontoF;
    private javax.swing.JTextField txtMontoI;
    // End of variables declaration//GEN-END:variables
}
